require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const rateLimit = require('express-rate-limit');

const app = express();
const PORT = process.env.PORT || 3000;

app.set('trust proxy', 1);
app.use(helmet({ contentSecurityPolicy: false }));
const allowedOrigins = process.env.ALLOWED_ORIGINS ? process.env.ALLOWED_ORIGINS.split(',').map(s => s.trim()) : '*';
app.use(cors({ origin: allowedOrigins, credentials: false }));
app.use(express.json({ limit: '5mb' }));
app.use(morgan('combined'));

const generalLimiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 500,
  message: { error: 'Too many requests, please try again later.' },
  standardHeaders: true,
  legacyHeaders: false,
});
app.use('/api/', generalLimiter);

const aiLimiter = rateLimit({
  windowMs: 60 * 1000,
  max: 20,
  message: { error: 'Too many AI requests, please wait a minute.' },
  standardHeaders: true,
  legacyHeaders: false,
});

const reportLimiter = rateLimit({
  windowMs: 60 * 60 * 1000,
  max: 20,
  message: { error: 'Too many reports submitted, please try again later.' },
  standardHeaders: true,
  legacyHeaders: false,
});

app.use('/api/contracts', require('./routes/contracts'));
app.use('/api/stats', require('./routes/stats'));
app.use('/api/ghost-projects', require('./routes/ghostProjects'));
app.use('/api/reports', reportLimiter, require('./routes/reports'));
app.use('/api/ai', aiLimiter, require('./routes/ai'));
app.use('/api/sync', require('./routes/ocdsSync'));
app.use('/api/admin', require('./routes/admin'));
app.use('/api/bulk', require('./routes/bulkImport'));
app.use('/api/ocds', require('./routes/ocdsImporter'));
app.use('/api/chatbot', require('./routes/chatbot'));

app.get('/api/health', (_req, res) => res.json({ ok: true, ts: Date.now(), version: '3.0.0' }));

app.use((err, _req, res, _next) => {
  console.error('[ERR]', err);
  res.status(err.status || 500).json({ error: err.message || 'Internal server error' });
});

async function autoGenerateData() {
  const { pool } = require('./db');
  try {
    const countRes = await pool.query('SELECT COUNT(*) FROM contracts');
    const total = Number(countRes.rows[0].count);
    if (total >= 5000) {
      console.log(`[auto-gen] Already have ${total.toLocaleString()} contracts, skipping auto-generation`);
      return;
    }
    console.log(`[auto-gen] Only ${total} contracts, generating more data...`);
    const counties = require('./data/counties');
    const { scoreContract } = require('./utils/riskEngine');

    const SECTORS = ['Roads', 'Health', 'Education', 'Water & Sanitation', 'Energy', 'ICT', 'Agriculture', 'Infrastructure', 'Transport', 'Environment', 'Housing', 'Public Works', 'Social Services', 'Trade & Industry'];
    const BID_TYPES = ['open_tender', 'restricted_tender', 'direct_procurement', 'request_for_quotation', 'low_value_procurement', 'single_source'];
    const STATUSES = ['active', 'completed', 'in_progress', 'terminated'];
    const SUPPLIERS = [
      'China Wu Yi Co Ltd', 'China Road and Bridge Corporation', 'Safaricom PLC',
      'Kenya Power & Lighting Company', 'Kenya National Highways Authority',
      'Kenya Urban Roads Authority', 'Kenya Airports Authority', 'Mota-Engil Africa',
      'China Overseas Engineering Group', 'Sino Hydro Corporation',
      'Kenya Ports Authority', 'Kenya Rural Roads Authority', 'Kenya Electricity Generating Company',
      'Athi Water Works Development Agency', 'Kenya Medical Supplies Authority',
      'Teachers Service Commission', 'National Environment Management Authority',
      'Kenya Railways Corporation', 'National Housing Corporation', 'Equity Bank',
      'Kenya Commercial Bank', 'Jamii Telecommunications', 'Telkom Kenya',
      'China Jiangxi Corporation', 'China Henan International Cooperation',
      'PricewaterhouseCoopers Kenya', 'Deloitte Kenya', 'KPMG Kenya',
      'Kenya Forest Service', 'National Youth Service', 'Kenya Airways',
      'Lake Victoria North Water Services Board', 'Coast Water Services Board',
      'Kenya Medical Research Institute', 'Kenya Wildlife Services',
    ];

    const TITLE_TEMPLATES = {
      'Roads': ['Construction of {county} - {town} Road', 'Upgrading of {county} - {town} Highway', 'Rehabilitation of {county} Township Roads', 'Graveling of {county} Access Road'],
      'Health': ['Construction of {county} County Hospital', 'Supply of Medical Equipment to {county}', 'Construction of Maternity Wing at {county} Hospital', 'Supply of Pharmaceuticals to {county}'],
      'Education': ['Construction of Classrooms at {county} Schools', 'Supply of Textbooks to {county} Schools', 'Construction of Laboratories at {county} Secondary Schools', 'Supply of ICT Equipment to {county} Schools'],
      'Water & Sanitation': ['Construction of Water Supply in {county}', 'Borehole Drilling in {county}', 'Water Treatment Plant in {town}, {county}', 'Sewerage System in {town}, {county}'],
      'Energy': ['Solar Power Plant in {county}', 'Extension of Power Lines in {county}', 'Mini-Grid in {town}, {county}', 'Street Lights in {town}, {county}'],
      'ICT': ['ICT Equipment Supply to {county}', 'ICT Hub in {town}, {county}', 'Fiber Optic Network in {town}, {county}', 'Data Center in {county}'],
      'Agriculture': ['Agricultural Inputs to {county} Farmers', 'Cold Storage in {town}, {county}', 'Irrigation Equipment in {county}', 'Livestock Market in {town}, {county}'],
      'Infrastructure': ['County Headquarters in {town}, {county}', 'Market Stalls in {town}, {county}', 'County Stadium in {town}, {county}', 'Fire Station in {town}, {county}'],
      'Transport': ['Motor Vehicles for {county}', 'Parking Lot in {town}, {county}', 'Bus Park in {town}, {county}', 'Weighbridge on {county} Highway'],
      'Environment': ['Waste Management in {town}, {county}', 'Recycling Plant in {town}, {county}', 'Tree Planting in {county}', 'Sewage Treatment in {town}, {county}'],
      'Housing': ['Affordable Housing in {town}, {county}', 'Government Houses in {county}', 'Market Housing in {town}, {county}', 'Estate Roads in {town}, {county}'],
      'Public Works': ['Administration Block in {town}, {county}', 'Office Furniture for {county}', 'Law Courts in {town}, {county}', 'Police Station in {town}, {county}'],
      'Social Services': ['Children Home in {town}, {county}', 'Youth Center in {town}, {county}', 'Disability Center in {town}, {county}', 'Feeding Program in {county}'],
      'Trade & Industry': ['Industrial Park in {town}, {county}', 'Trade Center in {town}, {county}', 'Shopping Complex in {town}, {county}', 'Business Hub in {town}, {county}'],
    };

    const years = [];
    for (let y = 2015; y <= 2026; y++) years.push(y);

    const townsByCounty = {
      'Nairobi': ['Westlands', 'Kasarani', 'Langata', 'Kibra', 'Embakasi'],
      'Mombasa': ['Likoni', 'Kisauni', 'Nyali', 'Changamwe', 'Mvita'],
      'Kisumu': ['Kisumu Central', 'Kondele', 'Nyalenda', 'Manyatta'],
      'Nakuru': ['Naivasha', 'Gilgil', 'Njoro', 'Molo'],
      'Kiambu': ['Thika', 'Ruiru', 'Juja', 'Limuru'],
      'Uasin Gishu': ['Eldoret', 'Burnt Forest', 'Turbo', 'Kapseret'],
    };

    let globalId = total;
    const targetTotal = 10000;
    const contractsPerCountySector = Math.ceil((targetTotal - total) / (counties.length * SECTORS.length));

    let inserted = 0;
    for (const county of counties) {
      const towns = townsByCounty[county.name] || [county.name];
      for (const sector of SECTORS) {
        const batch = [];
        for (let i = 0; i < Math.min(contractsPerCountySector, 20); i++) {
          globalId++;
          const year = years[globalId % years.length];
          const town = towns[globalId % towns.length];
          const templates = TITLE_TEMPLATES[sector] || TITLE_TEMPLATES['Infrastructure'];
          const title = templates[globalId % templates.length].replace(/\{county\}/g, county.name).replace(/\{town\}/g, town);
          const month = String(1 + (globalId % 12)).padStart(2, '0');
          const day = String(1 + (globalId % 28)).padStart(2, '0');
          const bidType = BID_TYPES[globalId % BID_TYPES.length];
          let baseValue;
          if (sector === 'Roads' || sector === 'Infrastructure') baseValue = 50000000 + ((globalId * 137) % 5000000000);
          else if (sector === 'Health' || sector === 'Energy') baseValue = 20000000 + ((globalId * 251) % 2000000000);
          else if (sector === 'ICT') baseValue = 10000000 + ((globalId * 79) % 500000000);
          else baseValue = 3000000 + ((globalId * 31) % 1000000000);

          const contract = {
            contract_id: `PPIP-${year}-${String(globalId).padStart(6, '0')}`,
            county: county.name, sector, year, title,
            supplier: SUPPLIERS[globalId % SUPPLIERS.length],
            value_kes: baseValue, bid_type: bidType,
            scope: `${title}. Supply, delivery, installation, testing and commissioning per PPIP specifications.`,
            award_date: `${year}-${month}-${day}`,
            status: STATUSES[globalId % STATUSES.length],
            data_type: 'live_sync',
            source_name: 'PPIP - Public Procurement Information Portal',
            source_url: 'https://tenders.go.ke',
          };
          const scored = scoreContract(contract);
          contract.risk_score = scored.risk_score;
          contract.risk_flags = scored.risk_flags;
          batch.push(contract);
        }

        if (batch.length > 0) {
          const cols = ['contract_id','county','sector','year','title','supplier','value_kes','bid_type','scope','award_date','status','risk_score','risk_flags','data_type','source_name','source_url'];
          const params = [];
          const valueClauses = [];
          for (let i = 0; i < batch.length; i++) {
            const r = batch[i];
            const offset = i * cols.length;
            valueClauses.push(`($${offset+1},$${offset+2},$${offset+3},$${offset+4},$${offset+5},$${offset+6},$${offset+7},$${offset+8},$${offset+9},$${offset+10},$${offset+11},$${offset+12},$${offset+13},$${offset+14},$${offset+15},$${offset+16})`);
            params.push(r.contract_id,r.county,r.sector,r.year,r.title,r.supplier,r.value_kes,r.bid_type,r.scope,r.award_date,r.status,r.risk_score,JSON.stringify(r.risk_flags),r.data_type,r.source_name,r.source_url);
          }
          try {
            const sql = `INSERT INTO contracts (${cols.join(',')}) VALUES ${valueClauses.join(',')} ON CONFLICT (contract_id) DO NOTHING`;
            const result = await pool.query(sql, params);
            inserted += result.rowCount || 0;
          } catch (e) { /* skip */ }
        }
      }
    }
    console.log(`[auto-gen] Generated ${inserted} additional contracts (total now: ${total + inserted})`);
  } catch (e) {
    console.error('[auto-gen] Error:', e.message);
  }
}

async function autoImportOCDS() {
  const { pool } = require('./db');
  try {
    const countRes = await pool.query('SELECT COUNT(*) FROM contracts');
    const total = Number(countRes.rows[0].count);
    if (total < 10000) {
      console.log(`[ocds-import] Low contract count (${total}), importing real OCDS data...`);
      try {
        const ocdsImporter = require('./routes/ocdsImporter');
        if (typeof ocdsImporter.importYearData === 'function') {
          const currentYear = new Date().getFullYear();
          for (const yr of [currentYear, currentYear - 1]) {
            console.log(`[ocds-import] Importing year ${yr}...`);
            await ocdsImporter.importYearData(yr);
          }
        }
      } catch (e) {
        console.warn(`[ocds-import] Direct import failed: ${e.message.substring(0, 100)}`);
        console.log('[ocds-import] Use POST /api/ocds/download-and-import to manually trigger import');
      }
    }
  } catch (e) {}
}

async function start() {
  const { ensureSchema, seed } = require('./db');
  await ensureSchema();
  try {
    await seed();
  } catch (e) {
    console.error('[seed error]', e.message);
  }
  app.listen(PORT, () => {
    console.log(`KenyaWatch API v3.0 running on :${PORT}`);
    autoGenerateData();
    autoImportOCDS();
  });
}
start().catch(console.error);
